### ISSUE TITLE
Pion derivative couplings not included?

### ISSUE THREAD

**Issue by LoganAMorrison** [LoganAMorrison/HazmaTools#1]
It appears as if the derivative couplings for the neutral pion are not included? For example, if I run:

```mathematica
<<HazmaTools`
$HazmaModel = "scalar";
HazmaComputeAmplitude[
  {NeutralPion, NeutralPion},
  {NeutralPion, NeutralPion},
  IncomingMomenta -> {p1, p2},
  OutgoingMomenta -> {p3, p4},
  ExcludeParticles -> {ScalarMediator}
  ] // InputForm
```

I get just:

```Mathematica
(b0*(mdq + muq))/fpi^2
```

Which looks to me like the derivative couplings aren't present (only the mass term.) But for the charged-pion:

```mathematica
HazmaComputeAmplitude[
 {ChargedPionM, ChargedPionP},
 {ChargedPionM, ChargedPionP},
 IncomingMomenta -> {p1, p2},
 OutgoingMomenta -> {p3, p4},
 ExcludeParticles -> {ScalarMediator, Photon}
 ]
```

I get:

```Mathematica
(2*b0*mdq + 2*b0*muq + Pair[Momentum[p1], 
   Momentum[p2]] - Pair[Momentum[p1], Momentum[p3]] + 
  2*Pair[Momentum[p1], Momentum[p4]] + 
  2*Pair[Momentum[p2], Momentum[p3]] - 
  Pair[Momentum[p2], Momentum[p4]] + 
  Pair[Momentum[p3], Momentum[p4]])/(3*fpi^2)
```

which seems to have the derivative couplings. @adam-coogan does this seem wrong to you? I don't want to dig around in the `FeynRules` model files unless this seem wrong.

**Comment by adam-coogan** [comment]
This is correct and happens because you can Wick contract any of the incoming and outgoing states with any of the fields in the relevant term in the Lagrangian. For example, it follows from using eq. A3 from [this reference](https://arxiv.org/pdf/1202.1532.pdf) and the fact that `A_s = (s - mπ^2) / fπ^2`.

**Comment by LoganAMorrison** [comment]
@adam-coogan Thanks. I agree with you. I checked that all those relations indeed hold in HazmaTools.
